apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # Base64 encoded string of: mongodb://mongo-service:27017/myapp
  MONGO_URI: mongodb+srv://t4technoshivam_db_user:dU32blpyvO8JyGB8@cluster0.akow2jv.mongodb.net/myapp