# 'as' ko 'AS' kar diya warning hatane ke liye
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve
FROM nginx:alpine

# MAGIC FIX: Yahan /app/build ki jagah /app/dist kar diya hai
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]