# Stage 1: Build
#FROM node:18-alpine AS build
FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./

RUN npm cache clean --force && npm ci --legacy-peer-deps

COPY . .

RUN npm run build

# Stage 2: Serve
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
